ecomm/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :stocks
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  

  authenticated :admin do
    root to: "admin#index", as: :admin_root
  end

  root "home#index"
  get "cart" => "carts#show"
  resources :categories, only: [:show]
  resources :products, only: [:show]
  get "admin" => "admin#index"
  
end

ecomm/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @main_categories = Category.take(4)
    end
end

ecomm/app/views/home/index.html.erb
<div class="bg-gray-800 text-white text-center py-20">
  <h1 class="text-5xl font-bold mb-4">Welcome to Ecomm</h1>
  <p class="text-xl mb-8">Your one-stop shop for all your e-commerce needs!</p>
  <%= link_to "Shop Now", root_path, class: "bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded" %>
</div>

<div class="flex flex-wrap justify-center mt-8 items-center gap-10">
  <% @main_categories.each do |category| %>
    <%= link_to category_path(category) do %>
      <div class="flex flex-col mb-4">
        <h2 class="text-gray-800 font-medium text-lg text-center mb-6"><%= category.name %></h2>
        <%= category.image.present? ? image_tag(category.image, class: "max-w-lg") : image_tag("http://via.placeholder.com/512") %>
      </div>
    <% end %>
  <% end %>
</div>

<div class="bg-gray-100 py-20 my-10">
  <div class="container mx-auto px-6">
    <h2 class="text-4xl font-bold text-center text-gray-800 mb-8">Customer Testimonials</h2>
    <div class="flex flex-wrap">
      <div class="w-full md:w-1/3 px-2 mb-4">
        <div class="bg-gray-100 rounded shadow py-4 px-4">
          <p class="text-gray-800 text-base mb-4">
            "I've been shopping on Ecomm for years, and it's always been a fantastic experience!"
          </p>
          <p class="text-gray-500 text-xs">
            - Jane Doe
          </p>
        </div>
      </div>
      <div class="w-full md:w-1/3 px-2 mb-4">
        <div class="bg-gray-100 rounded shadow py-4 px-4">
          <p class="text-gray-800 text-base mb-4">
            "I've been shopping on Ecomm for years, and it's always been a fantastic experience!"
          </p>
          <p class="text-gray-500 text-xs">
            - Jane Doe
          </p>
        </div>
      </div>
      <div class="w-full md:w-1/3 px-2 mb-4">
        <div class="bg-gray-100 rounded shadow py-4 px-4">
          <p class="text-gray-800 text-base mb-4">
            "I've been shopping on Ecomm for years, and it's always been a fantastic experience!"
          </p>
          <p class="text-gray-500 text-xs">
            - Jane Doe
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="bg-gray-500 text-white my-10 text-center py-20">
  <h2 class="text-3xl font-bold mb-6">Stay Updated</h2>
  <p class="mb-8">Subscribe to our newsletter for the latest updates and offers.</p>
  <%= form_with url: root_path, method: :post, local: true, class: "flex justify-center" do %>
    <%= email_field_tag :email, nil, placeholder: "Enter your email", class: "p-2 rounded-l text-gray-800" %>
    <%= submit_tag "Subscribe", class: "bg-gray-700 hover:bg-gray-800 cursor-pointer text-white font-bold py-2 px-4 rounded-r" %>
  <% end %>
</div>